/*
 * Copyright (C) 2015 Redjan Shabani
 * Contact: +355 69 84 93 238, redjan.shabani@gmail.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

/**
 *
 * @author user
 */
public class JPanelHeader extends javax.swing.JPanel
{

	/**
	 * Creates new form Header
	 */
	public JPanelHeader()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {
          java.awt.GridBagConstraints gridBagConstraints;

          jLabelDateTime = new javax.swing.JLabel();

          setBorder(javax.swing.BorderFactory.createEtchedBorder());
          setLayout(new java.awt.GridBagLayout());

          jLabelDateTime.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
          jLabelDateTime.setForeground(new java.awt.Color(0, 0, 255));
          jLabelDateTime.setText("<html><h1 align=\"center\" color=\"red\">00/00/0000 00:00:00</h1></html>");
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 0;
          gridBagConstraints.weightx = 1.0;
          gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
          add(jLabelDateTime, gridBagConstraints);
          Timer timer = new Timer(1000, new ActionListener()
               {
                    @Override
                    public void actionPerformed(ActionEvent e)
                    {
                         LocalDateTime now = LocalDateTime.now();
                         String timeStr = now.format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                         timeStr = "<html><h1 align=\"center\" color=\"red\">" + timeStr + "</h1></html>";
                         jLabelDateTime.setText(timeStr);
                    }
               });
               timer.start();
          }// </editor-fold>//GEN-END:initComponents


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel jLabelDateTime;
     // End of variables declaration//GEN-END:variables
}
