/*
 * Copyright (C) 2015 Redjan Shabani
 * Contact: +355 69 84 93 238, redjan.shabani@gmail.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gui;

/**
 *
 * @author Redjan Shabani
 */
public class JPanelFooter extends javax.swing.JPanel
{

	/**
	 * Creates new form JPanelFooter
	 */
	public JPanelFooter()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {
          java.awt.GridBagConstraints gridBagConstraints;

          jLabel1 = new javax.swing.JLabel();

          setBorder(javax.swing.BorderFactory.createEtchedBorder());
          setLayout(new java.awt.GridBagLayout());

          jLabel1.setText("<html> \t<p color=\"red\" align=\"center\">Copyrigh (C) 2015 Redjan Shabani</p> \t<p color=\"blue\" align=\"center\">Lagja \"Pavaresia\", Rruga \"Hektor Shyti\", Skele, Vlore (AL)</p> \t<p color=\"blue\" align=\"center\">+355 69 84 93 238 | redjan.shabani@gmail.com</p> </html>");
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
          add(jLabel1, gridBagConstraints);
     }// </editor-fold>//GEN-END:initComponents


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel jLabel1;
     // End of variables declaration//GEN-END:variables
}
