/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.task;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author user
 */
public class JPanelRejectCompleteTask extends javax.swing.JPanel
{

	/**
	 * Creates new form JPanelRejectCompleteTask
	 */
	public JPanelRejectCompleteTask()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {
          java.awt.GridBagConstraints gridBagConstraints;

          jScrollPane1 = new javax.swing.JScrollPane();
          jTextAreaDescription = new javax.swing.JTextArea();
          jLabel5 = new javax.swing.JLabel();
          jLabel1 = new javax.swing.JLabel();
          jXDatePickerExpiration = new org.jdesktop.swingx.JXDatePicker();

          setLayout(new java.awt.GridBagLayout());

          jTextAreaDescription.setColumns(50);
          jTextAreaDescription.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jTextAreaDescription.setLineWrap(true);
          jTextAreaDescription.setRows(25);
          jTextAreaDescription.setTabSize(5);
          jScrollPane1.setViewportView(jTextAreaDescription);

          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 3;
          gridBagConstraints.gridwidth = 2;
          gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
          gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
          add(jScrollPane1, gridBagConstraints);

          jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
          jLabel5.setText("Shenime");
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 2;
          gridBagConstraints.gridwidth = 2;
          gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
          add(jLabel5, gridBagConstraints);

          jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
          jLabel1.setText("Dt. e Mbylljes");
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 0;
          gridBagConstraints.gridy = 4;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
          gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
          add(jLabel1, gridBagConstraints);

          jXDatePickerExpiration.setDate(java.util.Date.from(Instant.now())
          );
          jXDatePickerExpiration.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
          jXDatePickerExpiration.setFormats("dd.MM.yyyy");
          gridBagConstraints = new java.awt.GridBagConstraints();
          gridBagConstraints.gridx = 1;
          gridBagConstraints.gridy = 4;
          gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
          gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
          add(jXDatePickerExpiration, gridBagConstraints);
          this.jXDatePickerExpiration.setDate(Date.from(Instant.now()));
     }// </editor-fold>//GEN-END:initComponents


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTextArea jTextAreaDescription;
     private org.jdesktop.swingx.JXDatePicker jXDatePickerExpiration;
     // End of variables declaration//GEN-END:variables

	public String getAnnotations()
	{
		return this.jTextAreaDescription.getText();
	}

	private LocalDateTime time = LocalDateTime.now();
	public LocalDateTime getEndtime()
	{
		return this.time;
	}
}
